language: node_js

node_js:
  - 9

cache:
  directories:
    - node_modules

script:
  - cd react-ui/ && npm install && npm install --only=dev --no-shrinkwrap && npm run test && CI=false npm run build

branches:
  only:
  - master